### ISSUE TITLE
Kubernetes plugin crashing

### ISSUE THREAD

**Issue by cmrust** [appoptics/kube-ao#2]
I'm occasionally seeing the Kubernetes AppOptics Plugin crash and not come back up. I've been able to raise the memory allocation for the pod and it delays the issue, for instance:

```
200Mi - 10m before crash
256Mi - 1hr before crash
350Mi - 8hr before crash
```
This last time around I raised it to 400Mi memory and it ran for 3-4 days without issue.

The memory usage chart in Grafana looks like this, where the wall around 20:57 is when metrics stopped arriving in AO:

![image 2](https://user-images.githubusercontent.com/1409650/36174164-0962a03c-10d1-11e8-92d9-e53d62a985fa.png)

And here's the logs it was printing around that time:

[kube-ao-log](https://github.com/appoptics/kube-ao/files/1721734/kube-ao-log.txt)

**Comment by cce** [comment]
@cmrust this is resolved now?

**Comment by cmrust** [comment]
Yes, @cce I believe it is. Submitting PR now to close it out.
